#!/bin/sh

export JAVA_OPTIONS="-Xmx128M -XX:PermSize=64M -XX:MaxPermSize=128M"
echo "JAVA_OPTIONS=$JAVA_OPTIONS"
echo '(To change JAVA_OPTIONS, edit the "run" script!)'

cd ~/$APPLICATION_FOLDER
target/start -Dconfig.resource=dotcloud.conf -DapplyEvolutions.default=true -Dhttp.port=$PORT_WWW
